name: cosc30_midterm_vallador_set4
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.20.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - images/color.jpg
    - images/login.jpg
    - images/log.jpg
    - images/ediwow.jpg
    - images/tutorial.jpg
      # Add the path to your MP3 file
